import { db } from "@/constants/firebase";
import { doc, serverTimestamp, setDoc } from "firebase/firestore";

const recipes = [
  {
    id: "pasta-carbonara",
    title: "Pasta Carbonara",
    description: "Clásica pasta italiana cremosa con tocino y queso",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800",
    prepTime: "20 min",
    servings: 4,
    difficulty: "Fácil",
    category: "Pasta",
    ingredients: [
      "400g de espagueti",
      "200g de tocino",
      "4 huevos",
      "100g de queso parmesano",
      "Pimienta negra",
      "Sal al gusto",
    ],
    instructions: [
      "Cocinar la pasta en agua con sal según el paquete",
      "Freír el tocino hasta que esté crujiente",
      "Batir los huevos con el parmesano",
      "Mezclar pasta con tocino",
      "Retirar del fuego y agregar huevo revolviendo rápido",
      "Servir con pimienta",
    ],
  },
  {
    id: "ensalada-cesar",
    title: "Ensalada César",
    description: "Fresca ensalada con pollo y aderezo cremoso",
    imageUrl: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800",
    prepTime: "15 min",
    servings: 2,
    difficulty: "Fácil",
    category: "Ensaladas",
    ingredients: [
      "1 lechuga romana",
      "2 pechugas de pollo",
      "Crutones",
      "50g de queso parmesano",
      "Aderezo César",
      "Aceite de oliva",
    ],
    instructions: [
      "Cocinar el pollo a la plancha",
      "Cortar la lechuga",
      "Cortar el pollo en tiras",
      "Mezclar lechuga con aderezo",
      "Agregar pollo, crutones y parmesano",
      "Servir",
    ],
  },
  {
    id: "tacos-al-pastor",
    title: "Tacos al Pastor",
    description: "Deliciosos tacos mexicanos con carne marinada y piña",
    imageUrl: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800",
    prepTime: "45 min",
    servings: 4,
    difficulty: "Media",
    category: "Mexicana",
    ingredients: [
      "500g de carne de cerdo",
      "1 piña fresca",
      "Tortillas de maíz",
      "Cebolla",
      "Cilantro",
      "Salsa de achiote",
      "Limón",
    ],
    instructions: [
      "Marinar la carne con achiote por 2 horas",
      "Cocinar la carne a fuego medio",
      "Cortar la piña en cubos pequeños",
      "Calentar las tortillas",
      "Servir la carne con piña, cebolla y cilantro",
      "Agregar limón al gusto",
    ],
  },
  {
    id: "pizza-margarita",
    title: "Pizza Margarita",
    description: "Pizza italiana clásica con tomate, mozzarella y albahaca",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
    prepTime: "30 min",
    servings: 2,
    difficulty: "Media",
    category: "Italiana",
    ingredients: [
      "Masa para pizza",
      "200g de salsa de tomate",
      "250g de mozzarella fresca",
      "Hojas de albahaca",
      "Aceite de oliva",
      "Sal",
    ],
    instructions: [
      "Estirar la masa en forma circular",
      "Esparcir la salsa de tomate",
      "Agregar la mozzarella en trozos",
      "Hornear a 220°C por 15 minutos",
      "Agregar albahaca fresca",
      "Rociar con aceite de oliva",
    ],
  },
  {
    id: "pollo-al-curry",
    title: "Pollo al Curry",
    description: "Cremoso curry de pollo con especias aromáticas",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800",
    prepTime: "35 min",
    servings: 4,
    difficulty: "Media",
    category: "India",
    ingredients: [
      "600g de pechuga de pollo",
      "400ml de leche de coco",
      "2 cucharadas de curry en polvo",
      "1 cebolla",
      "3 dientes de ajo",
      "Jengibre fresco",
      "Arroz basmati",
    ],
    instructions: [
      "Cortar el pollo en cubos",
      "Sofreír cebolla, ajo y jengibre",
      "Agregar el curry y cocinar 1 minuto",
      "Añadir el pollo y sellar",
      "Verter la leche de coco y cocinar 20 minutos",
      "Servir con arroz basmati",
    ],
  },
  {
    id: "hamburguesa-clasica",
    title: "Hamburguesa Clásica",
    description: "Jugosa hamburguesa con todos los ingredientes tradicionales",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    prepTime: "25 min",
    servings: 2,
    difficulty: "Fácil",
    category: "Americana",
    ingredients: [
      "400g de carne molida",
      "2 panes de hamburguesa",
      "Lechuga",
      "Tomate",
      "Cebolla",
      "Queso cheddar",
      "Salsa especial",
    ],
    instructions: [
      "Formar las hamburguesas con la carne",
      "Cocinar a fuego alto 4 minutos por lado",
      "Agregar el queso al final",
      "Tostar los panes",
      "Armar con lechuga, tomate y cebolla",
      "Agregar la salsa",
    ],
  },
  {
    id: "pancakes-americanos",
    title: "Pancakes Americanos",
    description: "Esponjosos pancakes perfectos para el desayuno",
    imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800",
    prepTime: "20 min",
    servings: 4,
    difficulty: "Fácil",
    category: "Desayunos",
    ingredients: [
      "2 tazas de harina",
      "2 huevos",
      "1 1/2 tazas de leche",
      "2 cucharadas de azúcar",
      "1 cucharadita de polvo de hornear",
      "Mantequilla",
      "Miel de maple",
    ],
    instructions: [
      "Mezclar ingredientes secos",
      "Batir huevos con leche",
      "Combinar ambas mezclas",
      "Cocinar en sartén con mantequilla",
      "Voltear cuando aparezcan burbujas",
      "Servir con miel de maple",
    ],
  },
  {
    id: "salmon-teriyaki",
    title: "Salmón Teriyaki",
    description: "Salmón glaseado con salsa teriyaki casera",
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800",
    prepTime: "25 min",
    servings: 2,
    difficulty: "Fácil",
    category: "Japonesa",
    ingredients: [
      "2 filetes de salmón",
      "4 cucharadas de salsa de soja",
      "2 cucharadas de mirin",
      "1 cucharada de azúcar",
      "Semillas de sésamo",
      "Cebollín",
      "Arroz blanco",
    ],
    instructions: [
      "Preparar salsa teriyaki mezclando soja, mirin y azúcar",
      "Sellar el salmón en sartén caliente",
      "Agregar la salsa teriyaki",
      "Cocinar hasta que glasee",
      "Decorar con sésamo y cebollín",
      "Servir con arroz",
    ],
  },
  {
    id: "risotto-champiñones",
    title: "Risotto de Champiñones",
    description: "Cremoso risotto italiano con variedad de hongos",
    imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800",
    prepTime: "40 min",
    servings: 4,
    difficulty: "Media",
    category: "Italiana",
    ingredients: [
      "300g de arroz arborio",
      "400g de champiñones mixtos",
      "1 litro de caldo de pollo",
      "1 cebolla",
      "100ml de vino blanco",
      "50g de queso parmesano",
      "Mantequilla",
    ],
    instructions: [
      "Sofreír cebolla en mantequilla",
      "Agregar arroz y tostar",
      "Añadir vino y dejar evaporar",
      "Agregar caldo poco a poco revolviendo",
      "Saltear champiñones aparte",
      "Mezclar todo con parmesano",
    ],
  },
  {
    id: "ceviche-peruano",
    title: "Ceviche Peruano",
    description: "Fresco ceviche de pescado con leche de tigre",
    imageUrl: "https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=800",
    prepTime: "30 min",
    servings: 4,
    difficulty: "Media",
    category: "Peruana",
    ingredients: [
      "500g de pescado blanco fresco",
      "10 limones",
      "1 cebolla morada",
      "Ají limo",
      "Cilantro",
      "Camote",
      "Choclo",
    ],
    instructions: [
      "Cortar el pescado en cubos",
      "Exprimir los limones",
      "Marinar el pescado por 5 minutos",
      "Agregar cebolla en juliana",
      "Añadir ají y cilantro",
      "Servir con camote y choclo",
    ],
  },
  {
    id: "lasagna-bolognesa",
    title: "Lasagna Bolognesa",
    description: "Capas de pasta con ragú y bechamel gratinada",
    imageUrl: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800",
    prepTime: "90 min",
    servings: 8,
    difficulty: "Difícil",
    category: "Italiana",
    ingredients: [
      "Láminas de lasagna",
      "500g de carne molida",
      "400g de salsa de tomate",
      "500ml de salsa bechamel",
      "200g de queso mozzarella",
      "Cebolla y zanahoria",
      "Vino tinto",
    ],
    instructions: [
      "Preparar el ragú bolognesa",
      "Preparar la salsa bechamel",
      "Alternar capas de pasta, ragú y bechamel",
      "Terminar con bechamel y queso",
      "Hornear a 180°C por 45 minutos",
      "Dejar reposar antes de servir",
    ],
  },
  {
    id: "omelette-francesa",
    title: "Omelette Francesa",
    description: "Clásico omelette cremoso y esponjoso",
    imageUrl: "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800",
    prepTime: "10 min",
    servings: 1,
    difficulty: "Fácil",
    category: "Desayunos",
    ingredients: [
      "3 huevos",
      "Mantequilla",
      "Sal",
      "Pimienta",
      "Hierbas finas",
      "Queso gruyère (opcional)",
    ],
    instructions: [
      "Batir los huevos ligeramente",
      "Calentar mantequilla en sartén",
      "Verter los huevos y mover suavemente",
      "Doblar cuando esté cremoso",
      "Servir de inmediato",
      "Decorar con hierbas",
    ],
  },
  {
    id: "brownie-chocolate",
    title: "Brownie de Chocolate",
    description: "Delicioso brownie húmedo con nueces",
    imageUrl: "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800",
    prepTime: "45 min",
    servings: 12,
    difficulty: "Fácil",
    category: "Postres",
    ingredients: [
      "200g de chocolate oscuro",
      "150g de mantequilla",
      "200g de azúcar",
      "3 huevos",
      "100g de harina",
      "100g de nueces",
      "1 cucharadita de vainilla",
    ],
    instructions: [
      "Derretir chocolate con mantequilla",
      "Batir huevos con azúcar",
      "Mezclar todo con la harina",
      "Agregar nueces",
      "Hornear a 180°C por 25 minutos",
      "Dejar enfriar antes de cortar",
    ],
  },
  {
    id: "smoothie-tropical",
    title: "Smoothie Tropical",
    description: "Refrescante batido de frutas tropicales",
    imageUrl: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800",
    prepTime: "5 min",
    servings: 2,
    difficulty: "Fácil",
    category: "Bebidas",
    ingredients: [
      "1 mango maduro",
      "1 plátano",
      "100g de piña",
      "200ml de leche de coco",
      "Hielo",
      "Miel al gusto",
    ],
    instructions: [
      "Pelar y trocear las frutas",
      "Agregar todos los ingredientes a la licuadora",
      "Licuar hasta obtener textura suave",
      "Ajustar dulzor con miel",
      "Servir frío",
      "Decorar con fruta fresca",
    ],
  },
  {
    id: "wrap-mediterraneo",
    title: "Wrap Mediterráneo",
    description: "Wrap saludable con hummus y vegetales frescos",
    imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800",
    prepTime: "15 min",
    servings: 2,
    difficulty: "Fácil",
    category: "Snacks",
    ingredients: [
      "2 tortillas de trigo",
      "100g de hummus",
      "1 pepino",
      "Tomates cherry",
      "Queso feta",
      "Aceitunas",
      "Espinacas",
    ],
    instructions: [
      "Untar hummus en la tortilla",
      "Agregar espinacas",
      "Añadir pepino y tomates",
      "Desmenuzar queso feta",
      "Agregar aceitunas",
      "Enrollar y servir",
    ],
  },
];

export async function seedRecipes() {
  for (const r of recipes) {
    await setDoc(doc(db, "recipes", r.id), {
      ...r,
      createdAt: serverTimestamp(),
    });
  }
  console.log("Recetas agregadas/actualizadas.");
}